version: '3.9'
services: 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # The port number, here, comes from the fact that
        # in the ports section after this one, we map 8080
        # on the local computer to 80 in the running
        # container.
        REACT_APP_API_URL: http://localhost:8080/api
    # This depends on backend because Nginx will stop if
    # it can't find the DNS entry named "backend" when
    # it starts
    depends_on: 
      - backend
    ports:
      - "8080:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on: 
      - postgres
    environment:
      PORT: 80
      JWT_SECRET: 29834rj9038qjf93erf8je9w8rfj98j324r8
      PGHOST: postgres
      PGPORT: 5432
      PGAPPNAME: Conference GO!

      # See the Dockerfile for the backend to understand
      # how the WAIT_HOSTS values are used
      WAIT_HOSTS: postgres:5432

      # Thes values are the same as below
      PGDATABASE: conference_app 
      PGUSER: conference_app_user
      PGPASSWORD: q390284nq4fdfq93
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: conference_app_user
      POSTGRES_PASSWORD: q390284nq4fdfq93
      POSTGRES_DB: conference_app
    volumes:
      - ./data:/var/lib/postgresql/data
